services:
  core-keeper:
    container_name: core-keeper-dedicated
    image: escaping/core-keeper-dedicated
    ports:
      - "27000:27050/tcp"
      - "27000:27050/udp"
    volumes:
      - server-files:/home/steam/core-keeper-dedicated
      - server-data:/home/steam/core-keeper-data
    env_file:
      - path: override.env
        required: false
    restart: unless-stopped
    stop_grace_period: 2m
volumes:
    server-files:
    server-data:
